# Generated by Django 3.2.22 on 2023-11-20 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='item_price',
        ),
    ]
